### ISSUE TITLE
No namespace for JwtSecurity

### ISSUE THREAD

**Issue by sgdunker** [Azure-Samples/power-bi-embedded-iframe#1]
I just downloaded the project and tried to simply build the project and I am getting missing references for 

JwtSecurityToken
JwtSecurityTokenHandler

Let me know how to fix this.

**Comment by wbreza** [comment]
There was a missing Nuget package reference.  Thanks for pointing this out.  Let us know if you run into any future issues.

**Comment by sgdunker** [comment]
Yep I just figured it out myself.  Thanks
